version: "3.9"

services:
  db:
    image: mariadb:latest
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=123456

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin
    ports:
      - "8080:80"
    restart: always

  blog:
    depends_on:
      - db
      - phpmyadmin
    image: php:7.4-apache
    ports:
      - "3333:80"
    volumes:
      - .:/var/www/html
    restart: always
volumes:
  web: